export const listAllCourse = [
  {
    id: 1,
    courseName: "UI Design",
    coursePrice: 300000,
    totalMaterial: 5,
    totalCourse: 5,
    totalMember: 10,
    category: "Category Design",
  },
  {
    id: 2,
    courseName: "Data Science",
    coursePrice: 200000,
    totalMaterial: 6,
    totalCourse: 4,
    totalMember: 10,
    category: "Category Bussiness",
  },
  {
    id: 3,
    courseName: "App Developer",
    coursePrice: 150000,
    totalMaterial: 6,
    totalCourse: 4,
    totalMember: 10,
    category: "Category Software",
  },
  {
    id: 4,
    courseName: "UI Design",
    coursePrice: 300000,
    totalMaterial: 5,
    totalCourse: 5,
    totalMember: 10,
    category: "Category Design",
  },
  {
    id: 5,
    courseName: "Data Science",
    coursePrice: 200000,
    totalMaterial: 6,
    totalCourse: 4,
    totalMember: 10,
    category: "Category Bussiness",
  },
  {
    id: 6,
    courseName: "App Developer",
    coursePrice: 150000,
    totalMaterial: 6,
    totalCourse: 4,
    totalMember: 10,
    category: "Category Software",
  },
  {
    id: 7,
    courseName: "UI Design",
    coursePrice: 300000,
    totalMaterial: 5,
    totalCourse: 5,
    totalMember: 10,
    category: "Category Design",
  },
  {
    id: 8,
    courseName: "Data Science",
    coursePrice: 200000,
    totalMaterial: 6,
    totalCourse: 4,
    totalMember: 10,
    category: "Category Bussiness",
  },
  {
    id: 9,
    courseName: "App Developer",
    coursePrice: 150000,
    totalMaterial: 6,
    totalCourse: 4,
    totalMember: 10,
    category: "Category Software",
  },
  {
    id: 10,
    courseName: "UI Design",
    coursePrice: 300000,
    totalMaterial: 5,
    totalCourse: 5,
    totalMember: 10,
    category: "Category Design",
  },
  {
    id: 11,
    courseName: "Data Science",
    coursePrice: 200000,
    totalMaterial: 6,
    totalCourse: 4,
    totalMember: 10,
    category: "Category Bussiness",
  },
  {
    id: 12,
    courseName: "App Developer",
    coursePrice: 150000,
    totalMaterial: 6,
    totalCourse: 4,
    totalMember: 10,
    category: "Category Software",
  },
];
